name: CI
on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          # package.json is not tracked so we can reuse pnpm global store
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true
          
  typecheck:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Run typecheck
        run: pnpm typecheck
        
  tests:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Run tests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'pnpm test -- --watchAll=false --ci'
          coverage-comment: false
          
  lint:
    runs-on: ubuntu-latest
    needs: prepare
    steps:       
      - name: Run linter
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{ts,tsx}'
          
  compile:
    runs-on: ubuntu-latest
    needs: prepare
    steps:     
      - name: Compile the code
        run: pnpm compile
        
  release:
    runs-on: ubuntu-latest
    needs: 
      - prepare
      - typecheck
      - tests
      - compile
    steps:       
      - name: Release
        run: pnpm release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
