name: Update contributors in the readme

on:
  push:
    branches:
      - main
      - master

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Update contributors in the readme
    steps:
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
