name: Update contributors in the readme

on:
  push:
    branches:
      - main
      - master

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: Update contributors in the readme
    steps:
      - name: Contribute List
        # https://github.com/akhilmhdh/contributors-readme-action
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'docs(contributor): contrib-readme-action has updated readme [skip ci]'
          use_username: true
          image_size: 50
